# ===== SITE SETTINGS ===== #

title: The VenHuizens
email: keith.venhuizen@gmail.com
description: >-
  Hello! We are The VenHuizens.

  Because our King is Jesus, our joy shines through and
  our words speak life. Our choices matter, our posture is humility and we give our
  lives to serve others.
baseurl: ""
url: "https://keithvenh.github.io/"
username: 
  github: keithvenh
  instagram: keithvenh
  cashapp: "$keithvenh"
  venmo: "@keithvenh"

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  
# Exclude from processing.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
