# ===== SITE SETTINGS ===== #

title: The VenHuizens
description: >-
  A website for the VenHuizen Family to spread the joy of their King Jesus to 
  their friends and family.
email: keith.venhuizen@gmail.com
mission: >-  
  Because our King is Jesus, our joy shines through and our words speak life. 
  Our choices matter, our posture is humility and we give our lives to serve others.
baseurl: ""
url: "https://keithvenh.github.io/"
username: 
  github: keithvenh
  instagram: keithvenh
  cashapp: "$keithvenh"
  venmo: "@keithvenh"

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  
collections:
  videos:
    output: true
  games:
    output: true  
# Exclude from processing.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
